### PR TITLE
added the feature of skipping by pressing the space key

### PR DESCRIPTION
**Pull request by soumitrapy**
I don't know anything about Javascript. :)
Thought it will be a good feature, so added it. It works fine in my desktop. (Can't say for mobile)

I can see one little problem here.
if someone choose to answer a question, and after choosing to answer if he again press the space key no problems occurs, but an error can be seen in the extension page, although it does not create any problem in the main work.
you guys please solve it....

### CODE REVIEW

**Comment by dalchandra** [comment]
Thank you, Soumitra, For contributing. It is an excellent idea. Nowadays, I am not using Chegg, and when I open Chegg for testing, there is no question available. As I think, and you also mentioned when we press space while typing the answer then it could cause an error or Skip the question which is not good. Try to solve the error by writing the condition for typing in the answer. You can attach the error screenshots by which I can get more idea that where is the error.

**Comment by soumitrapy** [comment]
Same situation here. If any question available in my page I will see the code again and send you the error. ( maybe in the midnight today). 

And one thing I wanna clarify, NO, after selecting to answer if someone press any space key. the question will not skip and it does not create any problem for the chegg expert. 

Ok I will send the error soon....

**Comment by soumitrapy** [comment]
Screenshot from 2023-05-23 00-28-36


Actually the problem exists from the beginning (in the skip function). You can see if after selecting to answer if you press the created skip button exactly this problem occurs.

So this is not a problem for this pull request. It was from the beginning.

**Comment by soumitrapy** [comment]
@dalchandra do you working on that?

**Pull request closed without merging**
